version: '3.5'

services:
  client:
    container_name: client
    build:
      context: ../client
      dockerfile: "Dockerfile.${RUN_MODE}"
      args:
        - NEXT_PUBLIC_SERVER_URL=${SERVER_URL}
    environment:
      - NEXT_PUBLIC_SERVER_URL=${SERVER_URL}
    ports:
      - '3000:3000'
    volumes:
      - "../client:/app"
      - "/app/node_modules"
    networks:
      - app-network

  server:
    container_name: server
    build:
      context: ../server
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - "../server:/app"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
