version: '3.5'

services:
  pose-game-ui:
    container_name: pose-game-ui
    build:
      context: ../pose_game_ui
      dockerfile: "Dockerfile.${RUN_MODE}"
      args:
        - NEXT_PUBLIC_SERVER_URL=${SERVER_URL}
    environment:
      - NEXT_PUBLIC_SERVER_URL=${SERVER_URL}
    ports:
      - '3000:3000'
    volumes:
      - "../pose_game_ui:/app"
      - "/app/node_modules"

  pose-game-server:
    container_name: pose_game_server
    build:
      context: ../pose_game_server
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - "../pose_game_server:/app"
